### ISSUE TITLE
Input box doesn't span the entire container

### ISSUE THREAD

**Issue by brarharjot** [brunoluiz/imagewand#5]
**The input box doesn't span the entire width of the container resulting in clicks not triggering the event on the right side.**

![image](https://user-images.githubusercontent.com/48310612/186154322-408b4dc0-90ab-41e0-a31e-291693a120b0.png)

**Comment by brunoluiz** [comment]
It seems a specific Firefox issue. I will push a fix to it, but as this was a toy project I haven't tried with Firefox or Safari as it was not the main goal of it.

![Screenshot 2022-08-27 at 00 53 47](https://user-images.githubusercontent.com/3219330/187005053-973abdd5-097b-4f3d-be20-3ed3c9042528.png)

**Comment by brunoluiz** [comment]
This should fix it: https://github.com/brunoluiz/imagewand/commit/a3d424cdf100a4159829a9d42d65bb9f8e1503a2
